version: '3'

services:
  code-server-gocv:
    image: gron1gh1/code-server-gocv
    environment:
      - PASSWORD=1q2w3e4r!
    volumes:
      - $PWD/data/code-server/config:/config
    restart: unless-stopped
    ports:
      - "80:80"
      - "8443:8443"
      - "8080:8080"
      - "49152-65535:49152-65535"
